#language: node_js
#node_js:
#  - lts/*
#install:
#  - npm install
#script:
#  - npm run build
#deploy:
#  provider: pages
#  skip_cleanup: true
#  local_dir: docs/.vuepress/dist
#  github_token: $TOKEN
#  keep_history: true
#  on:
#    branch: develop
language: java
script: mvn clean verify sonar:sonar -Pdev -Pdeploy -Pcoverage
install: true
addons:
  sonarcloud:
    organization: "sonarcloud"
    token:
      secure: "GD+gAxE233znLPGUtbMpQDf4u80hruTRO1wr2jrvYRHV4eH503ndoGdN3yfbXkxVEeu1DjN7uvODJDm35/BESqah1e8JcamFxyB/FMe7sT1gturo6vqcvVQeFoBxOPhLuAEX87te1EWMpdkNgPkhOH6W/m2hm56dDstty0vie3oBXZC5flXSghjYc/BjmxI33yxefp1xrKqwXKJ+AZMF7vytr00YyvlfQo+gDcrHWdeSbY1MHt5xRdSGCw7d7svNnBCywZf0GClPlcXf4fps9ehUKrlRTKlmUdPkpIRBDzbUHmVqyGCotwsz28frRT0A4FYLRui/kg458XmTfbNcgQB3Sp8QUrY40Bu2ZFvzdm/P67qGDzPBnmYCcigvXF1YS+NrtOPsXLItjQSnefl98ZtlMkPBiyOwjqk3KmouL79KVV5nQQdaz56V0tAiSSPlFk4vmi4P68QscHSB+NTUiwyCcla9BoYVsCq+HtJm6JkXlUSBvT0AhJ9Qwugmw03unRp5cF0IS3oimGkebL99dfm1kzaktsJiUC7uXCOhwseNBszXBhK0pQJFmNSu4JzWwo2qvNqMw6wV3pu94o1Zqony0K2mewk6gKRz0YTqubGKFH0n+wJNGq6svwb+7R+8gxdM7zqU2zCgJSWrb7/DtQTqPxCME1sTSbs6F+wl4xo="
before_install:
  - chmod +x mvnw
  - chmod +x docs/deploy.sh