#language: node_js
#node_js:
#  - lts/*
#install:
#  - npm install
#script:
#  - npm run build
#deploy:
#  provider: pages
#  skip_cleanup: true
#  local_dir: docs/.vuepress/dist
#  github_token: $TOKEN
#  keep_history: true
#  on:
#    branch: develop
language: java
script: mvn clean install -Pdev -Pdeploy
install: true
before_install:
  - chmod +x mvnw
  - chmod +x docs/deploy.sh