#language: node_js
#node_js:
#  - lts/*
#install:
#  - npm install
#script:
#  - npm run build
#deploy:
#  provider: pages
#  skip_cleanup: true
#  local_dir: docs/.vuepress/dist
#  github_token: $TOKEN
#  keep_history: true
#  on:
#    branch: develop
language: java
script: mvn clean verify sonar:sonar -Pdev -Pdeploy -Pcoverage
install: true
addons:
  sonarcloud:
    organization: "sonarcloud"
    token:
      secure: "HoKqV430gNWcchR2EpOcWH4+6uueYPCUOkOF7b2jjEDZ5xpcsy2VgwFM04rRM1uYDXf9LLGePAGqpnDPemoIpeS12RuFpIXG+zLBnJMbJoZBpMCEsXkXg/K8ekQJgO/NPJemkTtujoAGXa37AxZNWdBDgamHsWFMSIGr4+jh8CH5KMKE4G+9BA+wS92FOS1SLMzFblSfHqYZZR6IBFdGFrCUdHWR5UE3WuGzGzdgFGLYRY7Yr74oHYiNDGGZFDuXykUlmKjRptCDaV66PZtL0osJTjANEEashCgW/i9XGhnhmwbFIO6XG0r6kn0Hg6RKQbe/fo+ZXTfgcWg8fGMWUZwirGhIyfkK6tJ27+vqkbV5mp9w6T/8rvyilE07dU7NalCOgQ4ZTcpmpBipx8Mt7fCDFeHaGmOll0prmvy4SPsqCDp3REMv56fM/YUYpDHYCtERfV3jJhqArEBgZ0fyjYmNewiAic5gHZ6FjHrdQKojpeM6tnpj3ultD1ffQ4RdFWGE6kRuCw/O0wlD3G+1qjDr5Of9bcpmbesv8Tlvc+B76qy/Ua2dgMKrsrOputGm1IKhaC29PNrtmwRSx4Mu9oUOIO32v/bXdtI7BbIDolq3CyE9JLfcLXNCHjavcwDvs/j5hMXgUrvRw6Ji9uvnfQInZql11LSmJXWW0ERGWGE="
before_install:
  - chmod +x mvnw
  - chmod +x docs/deploy.sh