#language: node_js
#node_js:
#  - lts/*
#install:
#  - npm install
#script:
#  - npm run build
#deploy:
#  provider: pages
#  skip_cleanup: true
#  local_dir: docs/.vuepress/dist
#  github_token: $TOKEN
#  keep_history: true
#  on:
#    branch: develop
language: java
script: mvn clean verify sonar:sonar -Pdev -Pdeploy -Pcoverage -Dsonar.projectKey=h-wb_Pokapi -Dsonar.login="stHy1Z9MUMwbjRiFYaIPE3dJ1R4za3XNRKFKOT2RRRXL+5gYBLMVzZEUy/qIDKLj7E4v2Bu321ojptM0BMisvZtBN6TjHZa5x+OuHNxwkj9ay11Pf+p1sulQZYVE0OntKDNv5tV+Gj1Pcm+ILp/ZSGDSrpzCE90nK4WEY/33Wl02hKnqs6qiXYbjjLZxYVo2XAuMHe9XZukXoVr54WNEvX9bm6leKWMcI/zYg3jOQ4KTMliA3djvBKcLgyew5CXMAcHkUIjCCWAyZIB0bKwo+/KMtjmvkfBzfBOcurHeSg9QMYHC+dyO/wbKkCmO6ZOSnluVR8TOjQgDZtO017+RH54aK7mmCsNFjqC9IBt2AMxAgMNIb4kkkNRm2rVU5H7D2omBPbWrNmOQi9wtUeIWK/QckVLmHkSPIcjbnaEto8yx+WBbozzcKw98baQlcL/8ZI4DvcEA2fmqAdw5AT/VKXBAKzSO90WR2lVYxQCbr8SHFgHUmSdVuJJKujpyW2tbj6Hym65hwhle1k87UgQzZXewTyujMG7eQadIiLvgZNER8pQgz/OGiH8vB2Jrk82zV5uSmWfjF2WM5dh1SymO63Q1qRfe0uiqIgOsbr7MjB8kL5k1R75JL5QOOfBYC/OZF98oVuJqtfDMgASmsAxhopNfZ4xuph2YRRFCF0WoVo8="

install: true
addons:
  sonarcloud:
    organization: "sonarcloud"
    token:
      secure: "stHy1Z9MUMwbjRiFYaIPE3dJ1R4za3XNRKFKOT2RRRXL+5gYBLMVzZEUy/qIDKLj7E4v2Bu321ojptM0BMisvZtBN6TjHZa5x+OuHNxwkj9ay11Pf+p1sulQZYVE0OntKDNv5tV+Gj1Pcm+ILp/ZSGDSrpzCE90nK4WEY/33Wl02hKnqs6qiXYbjjLZxYVo2XAuMHe9XZukXoVr54WNEvX9bm6leKWMcI/zYg3jOQ4KTMliA3djvBKcLgyew5CXMAcHkUIjCCWAyZIB0bKwo+/KMtjmvkfBzfBOcurHeSg9QMYHC+dyO/wbKkCmO6ZOSnluVR8TOjQgDZtO017+RH54aK7mmCsNFjqC9IBt2AMxAgMNIb4kkkNRm2rVU5H7D2omBPbWrNmOQi9wtUeIWK/QckVLmHkSPIcjbnaEto8yx+WBbozzcKw98baQlcL/8ZI4DvcEA2fmqAdw5AT/VKXBAKzSO90WR2lVYxQCbr8SHFgHUmSdVuJJKujpyW2tbj6Hym65hwhle1k87UgQzZXewTyujMG7eQadIiLvgZNER8pQgz/OGiH8vB2Jrk82zV5uSmWfjF2WM5dh1SymO63Q1qRfe0uiqIgOsbr7MjB8kL5k1R75JL5QOOfBYC/OZF98oVuJqtfDMgASmsAxhopNfZ4xuph2YRRFCF0WoVo8="
before_install:
  - chmod +x mvnw
  - chmod +x docs/deploy.sh