version: '3.5'
services:
  groupe3:
    image: m2gi/groupe3:latest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m -XX:+UseSerialGC -Xss512k
    ports:
      - 9091:8080
    networks:
      - 'traefik-public'
    deploy:
      placement:
        constraints:
          - node.labels.target == fac
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
      restart_policy:
        max_attempts: 5
      labels:
        - traefik.frontend.rule=Host:groupe3.m2gi.win;PathPrefixStrip:/app/
        - traefik.enable=true
        - traefik.port=8080
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
    depends_on:
      - traefik

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    configs:
      - source: prometheus_conf8
        target: /etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - 'traefik-public'
    deploy:
      placement:
        constraints:
          - node.labels.target == fac
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
      restart_policy:
        max_attempts: 5
      labels:
        - traefik.frontend.rule=Host:groupe3.m2gi.win;PathPrefixStrip:/prom/
        - traefik.enable=true
        - traefik.port=9090
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
    depends_on:
      - traefik

  grafana:
    image: grafana/grafana:latest
    ports:
      - 9092:3000
    networks:
      - 'traefik-public'
    deploy:
      placement:
        constraints:
          - node.labels.target == fac
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
      restart_policy:
        max_attempts: 5
      labels:
        - traefik.frontend.rule=Host:groupe3.m2gi.win;Path:/grafana
        - traefik.enable=true
        - traefik.port=3000
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
    depends_on:
      - traefik

configs:
  prometheus_conf8:
    file: /var/jenkins_home/workspace/g3-psw/src/main/docker/prometheus.yml
networks:
  traefik-public:
    external: true
